inherit_from:
  - .rubocop-disable-default-enabled.yml
  - .rubocop-enable-default-disabled.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Security/Open:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/HashSyntax:
  Exclude:
    - lib/tasks/**/*.rake

Style/Lambda:
  EnforcedStyle: literal

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
